# fleet.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: simplewebpage-deployment
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: simplewebpage
      template:
        metadata:
          labels:
            app: simplewebpage
        spec:
          containers:
            - name: simplewebpage
              image: nikhil609651/simplewebpage
              ports:
                - containerPort: 80
      # Set the default namespace to "nginx" for resources in this file
      defaultNamespace: nginx

# simplewebpage-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simplewebpage-service
spec:
  selector:
    app: simplewebpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer   # Add this line to specify the service type as LoadBalancer
      defaultNamespace: nginx

  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: simplewebpage-ingress
    spec:
      rules:
        - host: simplewebpage.example.com   # Replace with your desired host/domain name
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: simplewebpage-service
                    port:
                      number: 80
      # Set the default namespace to "nginx" for resources in this file
      defaultNamespace: nginx
